version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: telemetry
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telemetry"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - ../storage/minio/data:/data
      - ../storage/minio/config:/root/.minio

  api:
    build:
      context: ..
      dockerfile: infra/python.Dockerfile
    command: uvicorn src.api.app:create_app --factory --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telemetry
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio12345
      S3_BUCKET: traces
      ENV: docker
    depends_on:
      - postgres
      - redis
      - minio
    ports: ["8000:8000"]

  worker:
    build:
      context: ..
      dockerfile: infra/python.Dockerfile
    command: python -m src.worker.main
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telemetry
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio12345
      S3_BUCKET: traces
      ENV: docker
    depends_on:
      - postgres
      - redis
      - minio

volumes:
  pgdata:

